"""Project Scaffold - 项目脚手架生成器"""
from pathlib import Path
from typing import Any, Dict, List, Optional


class ProjectScaffold:
    """生成项目脚手架"""

    DEFAULT_STRUCTURE = {
        "src": ["data", "models", "optimization", "gui"],
        "tests": ["unit", "integration"],
        "deployment": ["config"],
        "docs": ["api", "user_guide"],
        "experiments": ["runs", "results"]
    }

    def __init__(self, project_root: Path):
        self.project_root = project_root

    def create_structure(self, structure: Optional[Dict[str, List[str]]] = None) -> Dict[str, Any]:
        """创建项目结构"""
        if structure is None:
            structure = self.DEFAULT_STRUCTURE

        created_dirs = []

        for parent, children in structure.items():
            parent_path = self.project_root / parent
            parent_path.mkdir(parents=True, exist_ok=True)
            created_dirs.append(str(parent_path))

            for child in children:
                child_path = parent_path / child
                child_path.mkdir(parents=True, exist_ok=True)
                created_dirs.append(str(child_path))

        return {
            "status": "created",
            "directories": created_dirs
        }

    def create_init_files(self, base_dirs: Optional[List[str]] = None) -> Dict[str, Any]:
        """为所有目录创建 __init__.py 文件"""
        if base_dirs is None:
            base_dirs = ["src", "src/data", "src/models", "src/optimization", "src/gui", "tests", "tests/unit", "tests/integration"]

        created_files = []

        for dir_path in base_dirs:
            init_file = self.project_root / dir_path / "__init__.py"
            init_file.parent.mkdir(parents=True, exist_ok=True)

            if not init_file.exists():
                init_file.write_text(f'"""AutoEvolve {dir_path} package."""\n')
                created_files.append(str(init_file))

        return {
            "status": "created",
            "files": created_files
        }

    def generate_base_files(self) -> Dict[str, Any]:
        """生成基础文件"""
        files = {}

        # main.py
        files["main.py"] = '''"""AutoEvolve Project - Main Entry Point"""

def main():
    """Main entry point for the application."""
    print("AutoEvolve Project initialized.")


if __name__ == "__main__":
    main()
'''

        # src/__init__.py
        files["src/__init__.py"] = '"""AutoEvolve Project - Source Package."""\n'

        # src/data/__init__.py
        files["src/data/__init__.py"] = '"""Data processing module."""\n'

        # src/models/__init__.py
        files["src/models/__init__.py"] = '"""Models module."""\n'

        # README.md
        files["README.md"] = '''# AutoEvolve Generated Project

Generated by AutoEvolve Company AI Agent Team.

## Getting Started

```bash
pip install -r requirements.txt
python main.py
```
'''

        # requirements.txt
        files["requirements.txt"] = '''pandas>=1.5.0
numpy>=1.23.0
pytest>=7.0.0
'''

        # .gitignore
        files[".gitignore"] = '''__pycache__/
*.py[cod]
*$py.class
.env
.venv/
env/
venv/
*.egg-info/
dist/
build/
.pytest_cache/
.coverage
'''

        created = []
        for file_path, content in files.items():
            full_path = self.project_root / file_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)
            created.append(file_path)

        return {
            "status": "created",
            "files": created
        }

    def setup_project(self) -> Dict[str, Any]:
        """设置完整项目脚手架"""
        # 创建目录结构
        structure_result = self.create_structure()

        # 创建 __init__.py 文件
        init_result = self.create_init_files()

        # 生成基础文件
        files_result = self.generate_base_files()

        return {
            "status": "complete",
            "structure": structure_result["directories"],
            "init_files": init_result["files"],
            "base_files": files_result["files"]
        }